apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-yaixwafj
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-yaixwafj:c3422a23eb168077a97cc539b738a6af814407d6@sha256:baf9a42fd83b3781babce5253b163db9e39dc1d91f71edb6702a986b9f988e91
        name: container-image  
